### ISSUE TITLE
Nit: primitives is misspelled in py_ecc.bls module

### ISSUE THREAD

**Issue by prestwich** [ethereum/py_ecc#104]
# What is wrong?
 
Really small nit. `primitives` is incorrectly spelled `primatives` in `py_ecc.bls.g2_primatives`

**Comment by hwwhww** [comment]
Nice catch! 😮

Hmm, although it's a typo, we will have a backward-compatible issue if we just rename the file. Probably need to rename + add an alias `primatives` for compatibility. 😅

**Comment by prestwich** [comment]
I can put out a branch later today👌

**Comment by prestwich** [comment]
ugh I hit "close with comment" instead of just comment 🤣

**Comment by prestwich** [comment]
see #105

**Comment by pacrob** [comment]
closed by #105
