### ISSUE TITLE
stackoverflow while computing paring() on curve bn128

### ISSUE THREAD

**Issue by xingzhibo2019** [ethereum/py_ecc#120]
* OS: win10
* Python Version (python --version):3.8.5
* Environment (output of `pip freeze`):py-ecc==5.2.0

when compute paring(G2, G1), the process gives me "Process finished with exit code -1073741571 (0xC00000FD)", even i've set "threading.stack_size(200000000)", which doesn't work.
here's my test code:

import py_ecc.bn128.bn128_curve as curve
import py_ecc.bn128.bn128_pairing as pairing

def test():
    Z = pairing.pairing(curve.G2, curve.G1)
    print(Z)
    return

if __name__ == '__main__':
    threading.stack_size(200000000)
    thread = threading.Thread(target=test())
    thread.start()

a reasonable guess is that when computing __pow__()(which is in py_ecc/fields/field_properties.py) , the huge integer make the depth of stack too deep, which finally overflowed. but i still don't know how can i make it works.

**Comment by Devil-fire** [comment]
You can try to modify the__ pow__ (), as follows
```
    def __pow__(self, other):
        return self.pow(other)

    def pow(self, other):
        if other == 0:
            return self.__class__([1] + [0] * (self.degree - 1))
        elif other == 1:
            return self.__class__(self.coeffs)
        elif other % 2 == 0:
            base = self * self
            power = other // 2
            return (base).pow(power)
        else:
            base = self * self
            power = int(other // 2)
            return ((base).pow(power)) * self
```

**Comment by xingzhibo2019** [comment]
> You can try to modify the__ pow__ (), as follows
> 
> ```
>     def __pow__(self, other):
>         return self.pow(other)
> 
>     def pow(self, other):
>         if other == 0:
>             return self.__class__([1] + [0] * (self.degree - 1))
>         elif other == 1:
>             return self.__class__(self.coeffs)
>         elif other % 2 == 0:
>             base = self * self
>             power = other // 2
>             return (base).pow(power)
>         else:
>             base = self * self
>             power = int(other // 2)
>             return ((base).pow(power)) * self
> ```

**Comment by xingzhibo2019** [comment]
> You can try to modify the__ pow__ (), as follows
> 
> ```
>     def __pow__(self, other):
>         return self.pow(other)
> 
>     def pow(self, other):
>         if other == 0:
>             return self.__class__([1] + [0] * (self.degree - 1))
>         elif other == 1:
>             return self.__class__(self.coeffs)
>         elif other % 2 == 0:
>             base = self * self
>             power = other // 2
>             return (base).pow(power)
>         else:
>             base = self * self
>             power = int(other // 2)
>             return ((base).pow(power)) * self
> ```

thx!!! it works!!!

**Comment by 1zx999** [comment]
I had the same problem as you，i find the __ pow__ () function at py_ecc/fields/field_elements.py and i modify it ，but it still don't work。
