### ISSUE TITLE
py_ecc is very slow to import

### ISSUE THREAD

**Issue by charles-cooper** [ethereum/py_ecc#135]
### What happened?

py_ecc takes close to 1s to import. this increases startup time for anything which depends on py_ecc, including py-evm and titanoboa.

### Code that produced the error

```python
time python -c "import py_ecc"
```

### Fill this section in if you know how this could or should be fixed

Not exactly sure, but one thing that jumped out is py_ecc could stop doing so much during module initialization. there are a lot of assertions throughout py_ecc modules which take a lot of CPU time and frankly should only be done during testing.

### py-ecc Version

d5e5b2086483f9047cdaabf97eba7021bdf27168

### Python Version

python 3.10-3.12

**Comment by pacrob** [comment]
Spent the morning poking at it, but nothing solid to go on. You are correct, all the non-test `assert` lines should be replaced anyway. Will come back to it next week.

**Comment by pacrob** [comment]
@charles-cooper Does https://github.com/ethereum/py_ecc/pull/144 solve this for you?

**Comment by charles-cooper** [comment]
it helps somewhat! copied from discord:
```
(boa) ~/titanoboa $ time python -c "import boa"

real    0m1.080s
user    0m1.011s
sys    0m0.069s

py_ecc master (93edf6d654c06fff017ba77a103d59aae48edcd7)
(boa) ~/titanoboa $ time PYTHONPATH=~/src-references/py_ecc/ python -c "import boa"

real    0m0.739s
user    0m0.643s
sys    0m0.096s
```

it doesn't help that much for importing eth_account though, that is stuck at 300ms+
```
(test) ~ $ time python -c "import eth_account"
real    0m0.340s
user    0m0.304s
sys    0m0.036s
(test) ~ $ time PYTHONPATH=src-references/py_ecc/ python -c "import eth_account" 
real    0m0.343s
user    0m0.325s
sys    0m0.018s
```

**Comment by pacrob** [comment]
Looks good! I'll close this for now then. I don't see `py_ecc` in the `eth-account` dep tree, but you can open another issue over there if it's still a concern.
