### ISSUE TITLE
FQP initialization should take the mod of input coefficients

### ISSUE THREAD

**Issue by mratsim** [ethereum/py_ecc#47]
Full context: https://github.com/ethereum/eth2.0-specs/issues/508

### What is wrong?

For BN and BLS, FQP object should take the modulo of the input during initialization.

Test case:

```python
from py_ecc.optimized_bls12_381 import FQ, FQ2

x = FQ(-1)
y = FQ2([-1,-1])

print(x) # 4002409555221667393417789825735904156556882819939007885332058136124031650490837864442687629129015664037894272559786
print(y) # (-1, -1)
```

This is used in  `modular_squareroot` part of Eth2.0 spec (https://github.com/ethereum/eth2.0-specs/blob/928f9772fa51ed2e251b99c4795097da976c4bde/specs/bls_signature.md#modular_squareroot) and Trinity (https://github.com/ethereum/trinity/blob/a1b0f058e7bc8e385c8dac3164c49098967fd5bb/eth2/_utils/bls.py#L63-L77)

### How can it be fixed

Take the mod of the inputs in FQP `__init__`

https://github.com/ethereum/py_ecc/blob/e9c42c76f1cc4f535dedec01b4c7ab2a59e46119/py_ecc/optimized_bls12_381/optimized_field_elements.py#L126-L133

Like it's done for FQ

https://github.com/ethereum/py_ecc/blob/e9c42c76f1cc4f535dedec01b4c7ab2a59e46119/py_ecc/optimized_bls12_381/optimized_field_elements.py#L25-L31

**Comment by mratsim** [comment]
As mentioned in https://github.com/ethereum/eth2.0-specs/issues/508#issuecomment-458237139, it's the optimised implementation that has an issue:

```python
import py_ecc
x = py_ecc.bls12_381.FQ2([5,7])
y = py_ecc.bls12_381.FQ2([-x.coeffs[0], -x.coeffs[1]])
print(y.coeffs)


u = py_ecc.optimized_bls12_381.FQ2([5,7])
v = py_ecc.optimized_bls12_381.FQ2([-u.coeffs[0], -u.coeffs[1]])
print(v.coeffs)
```

**Comment by ChihChengLiang** [comment]
On this
